import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { communicationChannels, communicationStatuses, communicationStatusClass, communicationStatusLabel, communicationTypes } from "@/lib/reservation-communication";

export const dynamic = "force-dynamic";
type Row = { communication_id:string;reservation_id:string;restaurant_name:string;guest_name:string|null;guest_email:string|null;guest_phone:string|null;requested_date:string|null;requested_time:string|null;party_size:number|null;communication_type:string;channel:string;status:string;last_activity:string };
export default async function Page({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{business?:string;restaurant?:string;status?:string;type?:string;channel?:string}>}) {
 const {locale}=await params,q=await searchParams,supabase=await createClient();
 const {data:memberships=[]}=await supabase.from("business_memberships").select("business_id,businesses(name)");
 const businesses=(memberships||[]) as unknown as {business_id:string;businesses:{name:string}|{name:string}[]|null}[];
 const business=businesses.find(x=>x.business_id===q.business)||businesses[0];
 const {data:restaurants=[]}=business?await supabase.from("restaurants").select("id,name").eq("business_id",business.business_id).order("name"):{data:[]};
 const restaurant=(restaurants||[]).find(x=>x.id===q.restaurant);
 const result=business?await supabase.rpc("list_reservation_communication_queue",{p_business_id:business.business_id,p_restaurant_id:restaurant?.id||null,p_status:q.status||null,p_type:q.type||null,p_channel:q.channel||null}):{data:[],error:null};
 const rows=(result.data||[]) as Row[];
 return <div className="space-y-6 p-6 text-white"><header className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><p className="text-xs uppercase tracking-[0.2em] text-zinc-500">Reservation operations</p><h1 className="mt-2 text-3xl font-semibold">Guest Communications</h1><p className="mt-3 text-sm text-zinc-400">Prepare, review, and record guest communication. Nothing here dispatches through an external provider.</p></header>
 <form className="grid gap-3 rounded-2xl border border-white/10 bg-white/[0.02] p-5 md:grid-cols-3 xl:grid-cols-6"><label className="text-xs text-zinc-500">Business<select name="business" defaultValue={business?.business_id||""} className="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2">{businesses.map(x=><option key={x.business_id} value={x.business_id}>{Array.isArray(x.businesses)?x.businesses[0]?.name:x.businesses?.name}</option>)}</select></label><label className="text-xs text-zinc-500">Restaurant<select name="restaurant" defaultValue={restaurant?.id||""} className="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2"><option value="">All</option>{(restaurants||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><Filter name="status" label="Status" value={q.status} options={communicationStatuses}/><Filter name="type" label="Type" value={q.type} options={communicationTypes}/><Filter name="channel" label="Channel" value={q.channel} options={communicationChannels}/><div className="flex items-end"><button className="w-full rounded-lg bg-white px-4 py-2 text-sm font-medium text-black">Filter queue</button></div></form>
 {result.error?<p className="rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-red-200">{result.error.message}</p>:null}<section className="overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-full text-left text-sm"><thead className="bg-white/[0.03] text-xs uppercase tracking-wider text-zinc-500"><tr><th className="px-4 py-3">Guest</th><th className="px-4 py-3">Service</th><th className="px-4 py-3">Communication</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Last activity</th><th/></tr></thead><tbody className="divide-y divide-white/5">{rows.map(row=><tr key={row.communication_id}><td className="px-4 py-4"><p className="font-medium">{row.guest_name||"Guest"}</p><p className="text-xs text-zinc-500">{row.guest_email||row.guest_phone||"No contact recorded"} · {row.party_size??"—"} guests</p></td><td className="px-4 py-4">{row.restaurant_name}<p className="text-xs text-zinc-500">{row.requested_date||"Date pending"} · {row.requested_time?.slice(0,5)||"Time pending"}</p></td><td className="px-4 py-4 capitalize">{row.communication_type.replaceAll("_"," ")}<p className="text-xs text-zinc-500">{row.channel}</p></td><td className="px-4 py-4"><span className={`rounded-full border px-3 py-1 text-xs ${communicationStatusClass(row.status)}`}>{communicationStatusLabel(row.status)}</span></td><td className="px-4 py-4 text-zinc-400">{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(row.last_activity))}</td><td className="px-4 py-4 text-right"><Link href={`/${locale}/business/reservations/decisions/${row.reservation_id}`} className="rounded-lg border border-white/10 px-3 py-2 hover:bg-white/5">Open</Link></td></tr>)}{!rows.length?<tr><td colSpan={6} className="px-4 py-8 text-center text-zinc-500">No communications match these filters.</td></tr>:null}</tbody></table></section></div>;
}
function Filter({name,label,value,options}:{name:string;label:string;value?:string;options:readonly string[]}){return <label className="text-xs text-zinc-500">{label}<select name={name} defaultValue={value||""} className="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2"><option value="">All</option>{options.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label>}
