"use client";
import {useActionState,useRef} from "react";
import type {DecisionState} from "./actions";
import {acceptReservation,initialDecisionState,rejectReservation,returnReservationToPending} from "./actions";
const input="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-sm text-white";
function DecisionDialog({reservationId,title,buttonClass,action,reasonRequired,notesAllowed}:{reservationId:string;title:string;buttonClass:string;action:(state:DecisionState,data:FormData)=>Promise<DecisionState>;reasonRequired:boolean;notesAllowed:boolean}){
 const ref=useRef<HTMLDialogElement>(null);const [state,formAction,pending]=useActionState(action,initialDecisionState);
 return <><button type="button" onClick={()=>ref.current?.showModal()} className={buttonClass}>{title}</button><dialog ref={ref} className="m-auto w-full max-w-lg rounded-2xl border border-white/15 bg-zinc-950 p-0 text-white backdrop:bg-black/80"><form action={formAction} className="space-y-4 p-6"><input type="hidden" name="reservation_id" value={reservationId}/><h2 className="text-xl font-semibold">Confirm: {title}</h2><p className="text-sm text-zinc-400">This is an explicit human decision. No notification or other automated action will run.</p>{reasonRequired?<label className="block text-xs text-zinc-500">Reason (mandatory)<textarea name="reason" required maxLength={1000} className={input}/></label>:null}{notesAllowed?<label className="block text-xs text-zinc-500">Internal notes (optional)<textarea name="internal_notes" maxLength={2000} className={input}/></label>:null}{state.message?<p aria-live="polite" className={state.status==="error"?"text-sm text-red-300":"text-sm text-emerald-300"}>{state.message}</p>:null}<div className="flex justify-end gap-2"><button type="button" onClick={()=>ref.current?.close()} className="rounded-lg border border-white/10 px-4 py-2 text-sm">Cancel</button><button disabled={pending} className={buttonClass}>{pending?"Saving...":"Confirm decision"}</button></div></form></dialog></>;
}
export function DecisionControls({reservationId,status}:{reservationId:string;status:string}){return <section className="rounded-2xl border border-amber-300/25 bg-amber-300/[0.05] p-5"><p className="text-xs uppercase tracking-[0.18em] text-amber-200/70">Manual decision</p><h2 className="mt-2 text-xl font-semibold">Reservation Decision</h2><div className="mt-4 flex flex-wrap gap-3">{status!=="accepted"?<DecisionDialog reservationId={reservationId} title="Accept" action={acceptReservation} reasonRequired={false} notesAllowed buttonClass="rounded-lg bg-emerald-300 px-4 py-2 text-sm font-medium text-black disabled:opacity-50"/>:null}{status!=="rejected"?<DecisionDialog reservationId={reservationId} title="Reject" action={rejectReservation} reasonRequired notesAllowed buttonClass="rounded-lg bg-red-300 px-4 py-2 text-sm font-medium text-black disabled:opacity-50"/>:null}{status!=="pending"?<DecisionDialog reservationId={reservationId} title="Return To Pending" action={returnReservationToPending} reasonRequired notesAllowed={false} buttonClass="rounded-lg bg-amber-200 px-4 py-2 text-sm font-medium text-black disabled:opacity-50"/>:null}</div></section>}
