import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
export const dynamic="force-dynamic";
type Pending={reservation_id:string;business_id:string;restaurant_id:string;business_name:string;restaurant_name:string;guest_name:string;requested_date:string|null;requested_time:string|null;party_size:number|null;status:string;created_at:string};
export default async function DecisionQueue({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{business?:string;restaurant?:string}>}){
 const {locale}=await params,q=await searchParams,supabase=await createClient();
 const {data:memberships=[]}=await supabase.from("business_memberships").select("business_id,role,businesses(name)");
 const businesses=(memberships||[]) as unknown as {business_id:string;role:string;businesses:{name:string}|{name:string}[]|null}[];
 const business=businesses.find(x=>x.business_id===q.business)||businesses[0];
 const {data:restaurants=[]}=business?await supabase.from("restaurants").select("id,name").eq("business_id",business.business_id).order("name"):{data:[]};
 const restaurant=(restaurants||[]).find(x=>x.id===q.restaurant);
 const result=business?await supabase.rpc("list_pending_reservations",{p_business_id:business.business_id,p_restaurant_id:restaurant?.id||null}):{data:[],error:null};
 const rows=(result.data||[]) as Pending[];
 return <div className="space-y-6 p-6 text-white"><header className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><p className="text-xs uppercase tracking-[0.2em] text-zinc-500">Reservation operations</p><h1 className="mt-2 text-3xl font-semibold">Pending Review</h1><p className="mt-3 text-sm text-zinc-400">Human-only reservation decision queue. Nothing is automatically accepted, rejected, prioritized, or communicated.</p></header><form className="grid gap-3 rounded-2xl border border-white/10 bg-white/[0.02] p-5 md:grid-cols-3"><label className="text-xs text-zinc-500">Business<select name="business" defaultValue={business?.business_id||""} className="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2">{businesses.map(x=><option key={x.business_id} value={x.business_id}>{Array.isArray(x.businesses)?x.businesses[0]?.name:x.businesses?.name}</option>)}</select></label><label className="text-xs text-zinc-500">Restaurant<select name="restaurant" defaultValue={restaurant?.id||""} className="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2"><option value="">All restaurants</option>{(restaurants||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><div className="flex items-end"><button className="w-full rounded-lg bg-white px-4 py-2 text-sm font-medium text-black">Filter queue</button></div></form>{result.error?<p className="rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-red-200">{result.error.message}</p>:null}<section className="overflow-hidden rounded-2xl border border-white/10"><table className="min-w-full text-left text-sm"><thead className="bg-white/[0.03] text-xs uppercase tracking-wider text-zinc-500"><tr><th className="px-4 py-3">Guest</th><th className="px-4 py-3">Business / Restaurant</th><th className="px-4 py-3">Requested service</th><th className="px-4 py-3">Status</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-white/5">{rows.map(row=><tr key={row.reservation_id}><td className="px-4 py-4"><p className="font-medium">{row.guest_name}</p><p className="text-xs text-zinc-500">{row.party_size||"—"} guests</p></td><td className="px-4 py-4">{row.business_name}<p className="text-xs text-zinc-500">{row.restaurant_name}</p></td><td className="px-4 py-4">{row.requested_date||"Date pending"}<p className="text-xs text-zinc-500">{row.requested_time||"Time pending"}</p></td><td className="px-4 py-4"><span className="rounded-full border border-amber-300/30 bg-amber-300/10 px-3 py-1 text-amber-100">Pending Review</span></td><td className="px-4 py-4 text-right"><Link href={`/${locale}/business/reservations/decisions/${row.reservation_id}`} className="rounded-lg border border-white/10 px-3 py-2 hover:bg-white/5">Review</Link></td></tr>)}{!rows.length?<tr><td colSpan={5} className="px-4 py-8 text-center text-zinc-500">No reservations pending review.</td></tr>:null}</tbody></table></section></div>;
}
