import type {ReactNode} from "react";
import Link from "next/link";
import {notFound} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {BriefingControls} from "../briefing-controls";

export const dynamic="force-dynamic";
type Dietary={guest_name?:string;allergies?:string[];intolerances?:string[];dietary_restrictions?:string[];dislikes?:string[];notes?:string|null};
type Guest={guest_id:string;name:string|null;email:string|null;phone:string|null;is_host:boolean;position:number|null};
type Reservation={reservation_id:string;time:string|null;date:string|null;guest_name:string;guest_email:string|null;guest_phone:string|null;party_size:number|null;status:string;occasion:string|null;special_request:string|null;returning_guest:boolean;dietary:Dietary[];guests:Guest[];internal_notes:{id:string;note:string;created_at:string}[];communications:{id:string;type:string;channel:string;status:string;subject:string|null;updated_at:string}[];pending_updates:{id:string;type:string;summary:string;submitted_at:string}[];reviewed_updates:{id:string;type:string;summary:string;review_status:string;review_reason:string|null;reviewed_at:string}[];capacity_context:{availability_status?:string;override_reason?:string|null;operational_notes?:unknown[]}};
type Live={restaurant_name:string;service_date:string;service_period_name:string|null;summary:{accepted_reservations:number;covers:number;pending_guest_updates:number;communication_warnings:number;unresolved_warnings:number};reservations:Reservation[];capacity_context:unknown[]};
type Handoff={id:string;status:string;target_type:string;message:string|null;parent_handoff_id:string|null;created_at:string;acknowledged_at:string|null};
type Payload={briefing:{id:string;status:string;service_date:string;service_period_id:string|null;created_at:string;prepared_at:string|null;close_reason:string|null};live_briefing:Live;notes:{id:string;note:string;reservation_id:string|null;created_at:string}[];reviewed_items:{id:string;item_type:string;item_key:string;reservation_id:string|null;reviewed_at:string;review_note:string|null}[];handoffs:Handoff[];events:{id:string;event_type:string;old_status:string|null;new_status:string|null;created_at:string}[]};
export default async function BriefingDetail({params}:{params:Promise<{locale:string;id:string}>}){
 const {locale,id}=await params,supabase=await createClient();const {data,error}=await supabase.rpc("get_pre_service_briefing",{p_briefing_id:id});
 if(error||!data)notFound();const payload=data as Payload,live=payload.live_briefing,reservations=live.reservations||[];
 const text=briefingText(live,payload);
 return <div className="space-y-6 p-6 text-white"><div><Link href={`/${locale}/business/briefings`} className="text-sm text-zinc-400 hover:text-white">← Back to briefings</Link></div><header className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><p className="text-xs uppercase tracking-[0.2em] text-zinc-500">Pre-service briefing</p><div className="mt-2 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold">{live.restaurant_name}</h1><Badge value={payload.briefing.status}/></div><p className="mt-3 text-sm text-zinc-400">{live.service_date} · {live.service_period_name||"All periods"}. Human-controlled briefing; pending guest updates are shown only as items requiring review.</p></header>
  <BriefingControls briefingId={payload.briefing.id} status={payload.briefing.status} handoffs={payload.handoffs||[]} reservations={reservations.map(r=>({reservation_id:r.reservation_id,guest_name:r.guest_name}))} briefingText={text}/>
  <section className="grid gap-4 md:grid-cols-5"><Metric label="Reservations" value={live.summary.accepted_reservations}/><Metric label="Covers" value={live.summary.covers}/><Metric label="Pending updates" value={live.summary.pending_guest_updates}/><Metric label="Communication warnings" value={live.summary.communication_warnings}/><Metric label="Warnings" value={live.summary.unresolved_warnings}/></section>
  <Section title="Reservations ordered by service time">{reservations.length?reservations.map(r=><article key={r.reservation_id} className="rounded-xl border border-white/10 p-4"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-medium">{r.time?.slice(0,5)||"Time pending"} · {r.guest_name} · {r.party_size??"—"} guests</h3><p className="text-xs text-zinc-500">{r.guest_email||r.guest_phone||"No contact"} · {r.returning_guest?"Returning guest":"First known visit"}</p></div><Link href={`/${locale}/business/reservations/decisions/${r.reservation_id}`} className="text-sm text-zinc-400 hover:text-white">Open reservation</Link></div><div className="mt-3 grid gap-3 md:grid-cols-3"><Mini title="Special context" items={[r.occasion,r.special_request].filter(Boolean) as string[]}/><Mini title="Dietary / guests" items={[`${r.dietary?.length||0} dietary profiles`,`${r.guests?.length||0} linked guests`]}/><Mini title="Capacity" items={[r.capacity_context?.availability_status||"No status",r.capacity_context?.override_reason||"No active override"]}/></div></article>):<Empty text="No accepted reservations found for this operational scope."/>}</Section>
  <Section title="Dietary, allergies and restrictions">{reservations.flatMap(r=>(r.dietary||[]).map((d,i)=><div key={`${r.reservation_id}-${i}`} className="rounded-xl border border-white/10 p-4"><p className="font-medium">{r.guest_name} {d.guest_name?`· ${d.guest_name}`:""}</p><p className="mt-2 text-sm text-zinc-400">Allergies: {list(d.allergies)} · Intolerances: {list(d.intolerances)} · Restrictions: {list(d.dietary_restrictions)} · Dislikes: {list(d.dislikes)}</p>{d.notes?<p className="mt-2 text-sm text-zinc-300">{d.notes}</p>:null}</div>)).length?reservations.flatMap(r=>(r.dietary||[]).map((d,i)=><div key={`${r.reservation_id}-${i}`} className="rounded-xl border border-white/10 p-4"><p className="font-medium">{r.guest_name} {d.guest_name?`· ${d.guest_name}`:""}</p><p className="mt-2 text-sm text-zinc-400">Allergies: {list(d.allergies)} · Intolerances: {list(d.intolerances)} · Restrictions: {list(d.dietary_restrictions)} · Dislikes: {list(d.dislikes)}</p>{d.notes?<p className="mt-2 text-sm text-zinc-300">{d.notes}</p>:null}</div>)):<Empty text="No dietary profiles attached to these accepted reservations."/>}</Section>
  <Section title="Pending guest updates requiring review">{reservations.some(r=>r.pending_updates?.length)?reservations.flatMap(r=>(r.pending_updates||[]).map(u=><div key={u.id} className="rounded-xl border border-amber-300/20 bg-amber-300/5 p-4"><p className="font-medium text-amber-100">{r.guest_name} · {u.type.replaceAll("_"," ")}</p><p className="mt-2 text-sm text-zinc-300">{u.summary}</p><p className="mt-2 text-xs text-zinc-500">Not approved for operational context until reviewed in Guest Updates.</p></div>)):<Empty text="No pending guest updates."/>}</Section>
  <Section title="Reviewed guest updates approved for context">{reservations.some(r=>r.reviewed_updates?.length)?reservations.flatMap(r=>(r.reviewed_updates||[]).map(u=><div key={u.id} className="rounded-xl border border-white/10 p-4"><p className="font-medium">{r.guest_name} · {u.review_status.replaceAll("_"," ")}</p><p className="mt-2 text-sm text-zinc-300">{u.summary}</p>{u.review_reason?<p className="mt-2 text-xs text-zinc-500">Review note: {u.review_reason}</p>:null}</div>)):<Empty text="No reviewed guest updates for this briefing."/>}</Section>
  <Section title="Communications readiness">{reservations.map(r=><div key={r.reservation_id} className="rounded-xl border border-white/10 p-4"><p className="font-medium">{r.guest_name}</p><p className="mt-1 text-sm text-zinc-400">{r.communications.some(c=>c.status==="marked_sent")?"At least one communication marked sent":"No sent communication recorded"}</p>{r.communications.length?<ul className="mt-3 space-y-1 text-sm text-zinc-400">{r.communications.map(c=><li key={c.id}>{c.type} · {c.channel} · {c.status}{c.subject?` · ${c.subject}`:""}</li>)}</ul>:null}</div>)}</Section>
  <Section title="Briefing notes, reviews and handoff audit"><div className="grid gap-4 lg:grid-cols-3"><Audit title="Notes" rows={(payload.notes||[]).map(n=>`${new Date(n.created_at).toLocaleString(locale)} · ${n.note}`)}/><Audit title="Reviewed items" rows={(payload.reviewed_items||[]).map(i=>`${i.item_type}: ${i.item_key}`)}/><Audit title="Events" rows={(payload.events||[]).map(e=>`${new Date(e.created_at).toLocaleString(locale)} · ${e.event_type} (${e.old_status||"—"} → ${e.new_status||"—"})`)}/></div></Section>
 </div>;
}
function Metric({label,value}:{label:string;value:number}){return <div className="rounded-2xl border border-white/10 bg-white/[0.03] p-4"><p className="text-xs uppercase tracking-wider text-zinc-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>}
function Section({title,children}:{title:string;children:ReactNode}){return <section className="space-y-3 rounded-2xl border border-white/10 bg-white/[0.02] p-5"><h2 className="text-lg font-semibold">{title}</h2>{children}</section>}
function Mini({title,items}:{title:string;items:string[]}){return <div><p className="text-xs uppercase tracking-wider text-zinc-500">{title}</p>{items.length?<ul className="mt-1 space-y-1 text-sm text-zinc-300">{items.map(x=><li key={x}>{x}</li>)}</ul>:<p className="mt-1 text-sm text-zinc-500">None</p>}</div>}
function Audit({title,rows}:{title:string;rows:string[]}){return <div><h3 className="font-medium">{title}</h3>{rows.length?<ul className="mt-2 space-y-2 text-sm text-zinc-400">{rows.map((x,i)=><li key={`${title}-${i}`}>{x}</li>)}</ul>:<p className="mt-2 text-sm text-zinc-500">None recorded.</p>}</div>}
function Empty({text}:{text:string}){return <p className="rounded-xl border border-white/10 p-4 text-sm text-zinc-500">{text}</p>}
function Badge({value}:{value:string}){return <span className="rounded-full border border-emerald-300/30 bg-emerald-300/10 px-3 py-1 text-xs text-emerald-100">{value.replaceAll("_"," ")}</span>}
function list(value:unknown){return Array.isArray(value)&&value.length?value.join(", "):"none recorded"}
function briefingText(live:Live,payload:Payload){return [`${live.restaurant_name} briefing`,`${live.service_date} · ${live.service_period_name||"All periods"}`,`Status: ${payload.briefing.status}`,`Reservations: ${live.summary.accepted_reservations}; Covers: ${live.summary.covers}`,`Warnings: ${live.summary.unresolved_warnings}`,...(live.reservations||[]).map(r=>`${r.time?.slice(0,5)||"—"} ${r.guest_name} (${r.party_size??"—"})${r.returning_guest?" returning":""}`)].join("\n");}
