"use client";

import {useActionState,useRef,useState} from "react";
import {generateConfirmationLink,initialConfirmationAccessState,revokeConfirmationLink,type ConfirmationAccessState} from "./confirmation-actions";
import type {ConfirmationTokenRecord} from "@/lib/guest-confirmation";

const input="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-sm text-white";
function Feedback({state}:{state:ConfirmationAccessState}){return state.message?<p aria-live="polite" className={state.status==="error"?"text-sm text-red-300":"text-sm text-emerald-300"}>{state.message}</p>:null}
export function ConfirmationAccessControls({reservationId,tokens}:{reservationId:string;tokens:ConfirmationTokenRecord[]}){
 const [state,action,pending]=useActionState(generateConfirmationLink,initialConfirmationAccessState);const active=tokens.find(x=>!x.revoked_at&&new Date(x.expires_at)>new Date());
 return <div className="space-y-4"><div className="flex flex-wrap items-center gap-3"><span className={`rounded-full border px-3 py-1 text-xs ${active?"border-emerald-300/30 bg-emerald-300/10 text-emerald-100":"border-zinc-500/30 bg-zinc-500/10 text-zinc-300"}`}>{active?"Confirmation link active":"No active confirmation link"}</span>{active?<span className="text-xs text-zinc-500">Expires {new Date(active.expires_at).toLocaleString()} · {active.view_count} views</span>:null}</div>
 <form action={action} className="space-y-3"><input type="hidden" name="reservation_id" value={reservationId}/><button disabled={pending} className="rounded-lg bg-sky-200 px-4 py-2 text-sm font-medium text-black disabled:opacity-50">{pending?"Generating...":active?"Regenerate confirmation link":"Generate confirmation link"}</button><p className="text-xs text-zinc-500">Regenerating immediately revokes the previous link. Nothing is sent automatically.</p><Feedback state={state}/>{state.confirmationPath?<CopyLink path={state.confirmationPath}/>:null}</form>
 {active?<Revoke token={active}/>:null}<div className="space-y-2">{tokens.map(token=><div key={token.id} className="rounded-lg border border-white/10 bg-black/20 p-3 text-xs text-zinc-400"><span className={token.revoked_at?"text-red-300":"text-emerald-300"}>{token.revoked_at?"Revoked":"Active when unexpired"}</span> · created {new Date(token.created_at).toLocaleString()}{token.revocation_reason?` · ${token.revocation_reason}`:""}</div>)}</div></div>;
}
function CopyLink({path}:{path:string}){const [copied,setCopied]=useState(false);return <div className="flex gap-2"><input readOnly value={path} className={input}/><button type="button" onClick={async()=>{await navigator.clipboard.writeText(`${window.location.origin}${path}`);setCopied(true)}} className="rounded-lg border border-white/15 px-3 py-2 text-sm">{copied?"Copied":"Copy link"}</button></div>}
function Revoke({token}:{token:ConfirmationTokenRecord}){const ref=useRef<HTMLDialogElement>(null);const [state,action,pending]=useActionState(revokeConfirmationLink,initialConfirmationAccessState);return <><button type="button" onClick={()=>ref.current?.showModal()} className="rounded-lg border border-red-300/30 px-3 py-2 text-sm text-red-200">Revoke link</button><dialog ref={ref} className="m-auto w-full max-w-lg rounded-2xl border border-white/15 bg-zinc-950 p-0 text-white backdrop:bg-black/80"><form action={action} className="space-y-4 p-6"><input type="hidden" name="token_id" value={token.id}/><h3 className="text-xl font-semibold">Revoke confirmation link</h3><p className="text-sm text-zinc-400">The guest will immediately lose access. This does not change the reservation status.</p><label className="block text-xs text-zinc-500">Reason (mandatory)<textarea name="reason" required maxLength={1000} className={input}/></label><Feedback state={state}/><div className="flex justify-end gap-2"><button type="button" onClick={()=>ref.current?.close()} className="rounded-lg border border-white/10 px-4 py-2 text-sm">Back</button><button disabled={pending} className="rounded-lg bg-red-200 px-4 py-2 text-sm font-medium text-black">{pending?"Revoking...":"Confirm revoke"}</button></div></form></dialog></>}
