import {createClient} from "@/lib/supabase/server";
import Link from "next/link";
import type {ConfirmationTokenRecord,GuestSubmission} from "@/lib/guest-confirmation";
import {ConfirmationAccessControls} from "./confirmation-access-controls";

export async function GuestConfirmationAccess({reservationId,reservationStatus,locale}:{reservationId:string;reservationStatus:string;locale:string}){
 const supabase=await createClient();
 const [tokenResult,submissionResult,reviewResult]=await Promise.all([
  supabase.from("reservation_confirmation_tokens").select("id,reservation_id,created_at,expires_at,revoked_at,revocation_reason,last_viewed_at,view_count").eq("reservation_id",reservationId).order("created_at",{ascending:false}),
  supabase.from("reservation_guest_submissions").select("id,submission_type,preferred_channel,preferred_language,can_contact_about_reservation,allergies_dietary_note,special_occasion_note,arrival_accessibility_note,general_note,review_status,created_at").eq("reservation_id",reservationId).order("created_at",{ascending:false}),
  supabase.from("reservation_guest_submission_reviews").select("submission_id,review_status").eq("reservation_id",reservationId)
 ]);
 const tokens=(tokenResult.data||[]) as ConfirmationTokenRecord[],submissions=(submissionResult.data||[]) as GuestSubmission[];
 const reviews=new Map((reviewResult.data||[]).map(item=>[item.submission_id,item.review_status]));
 return <section className="space-y-4 rounded-2xl border border-violet-300/20 bg-violet-300/[0.04] p-5"><div><p className="text-xs uppercase tracking-[0.18em] text-violet-200/70">Guest-safe access</p><h2 className="mt-2 text-xl font-semibold">Confirmation View & Preferences</h2><p className="mt-2 text-sm text-zinc-400">Manage the private guest link and review guest-provided updates. Guest input never changes operational status.</p></div>
 {reservationStatus==="accepted"?<ConfirmationAccessControls reservationId={reservationId} tokens={tokens}/>:<p className="rounded-xl border border-white/10 bg-black/20 p-4 text-sm text-zinc-400">Guest confirmation access is available only while the reservation is accepted.</p>}
 <div><h3 className="text-sm font-medium uppercase tracking-[0.15em] text-zinc-500">Guest submissions</h3><div className="mt-3 space-y-3">{submissions.filter(item=>!reviews.has(item.id)).map(item=><Submission key={item.id} item={item}/>)}{submissions.filter(item=>reviews.has(item.id)).map(item=><Link key={item.id} href={`/${locale}/business/guest-updates/${item.id}`} className="block rounded-xl border border-emerald-300/20 bg-emerald-300/[0.04] p-3 text-sm text-emerald-100">{reviews.get(item.id)?.replaceAll("_"," ")} ? view reviewed update</Link>)}{!submissions.length?<p className="text-sm text-zinc-500">No guest updates received.</p>:null}</div></div>
 </section>;
}
function Submission({item}:{item:GuestSubmission}){return <article className="rounded-xl border border-white/10 bg-black/25 p-4 text-sm"><div className="flex flex-wrap items-center justify-between gap-2"><p className="font-medium">{item.submission_type==="communication_preferences"?"Preference update received":"Guest update received"}</p><span className="rounded-full border border-amber-300/30 bg-amber-300/10 px-3 py-1 text-xs text-amber-100">Pending review</span></div><p className="mt-1 text-xs text-zinc-500">{new Date(item.created_at).toLocaleString()}</p>{item.submission_type==="communication_preferences"?<p className="mt-3 text-zinc-300">Channel: {item.preferred_channel} · Language: {item.preferred_language} · Contact permitted: {item.can_contact_about_reservation?"Yes":"No"}</p>:<div className="mt-3 space-y-1 text-zinc-300">{item.allergies_dietary_note?<p><span className="text-zinc-500">Allergies / dietary:</span> {item.allergies_dietary_note}</p>:null}{item.special_occasion_note?<p><span className="text-zinc-500">Occasion:</span> {item.special_occasion_note}</p>:null}{item.arrival_accessibility_note?<p><span className="text-zinc-500">Arrival / accessibility:</span> {item.arrival_accessibility_note}</p>:null}{item.general_note?<p><span className="text-zinc-500">General:</span> {item.general_note}</p>:null}</div>}</article>}
