import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
export const dynamic="force-dynamic";
type Row={submission_id:string;reservation_id:string;restaurant_name:string;guest_name:string;guest_email:string|null;guest_phone:string|null;reservation_date:string|null;reservation_time:string|null;party_size:number|null;update_type:string;preview:string;submitted_at:string;review_status:string};
const statuses=["pending_review","accepted","dismissed","converted_to_internal_note","converted_to_communication_task"];
export default async function GuestUpdatesQueue({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{business?:string;restaurant?:string;date?:string;status?:string;type?:string}>}){
 const {locale}=await params,q=await searchParams,supabase=await createClient();
 const {data:memberships=[]}=await supabase.from("business_memberships").select("business_id,businesses(name)");
 const businesses=(memberships||[]) as unknown as {business_id:string;businesses:{name:string}|{name:string}[]|null}[];
 const business=businesses.find(x=>x.business_id===q.business)||businesses[0];
 const {data:restaurants=[]}=business?await supabase.from("restaurants").select("id,name").eq("business_id",business.business_id).order("name"):{data:[]};
 const restaurant=(restaurants||[]).find(x=>x.id===q.restaurant);
 const result=business?await supabase.rpc("list_guest_update_reviews",{p_business_id:business.business_id,p_restaurant_id:restaurant?.id||null,p_service_date:q.date||null,p_status:q.status||"pending_review",p_update_type:q.type||null}):{data:[],error:null};
 const rows=(result.data||[]) as Row[];
 return <div className="space-y-6 p-6 text-white"><header className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><p className="text-xs uppercase tracking-[0.2em] text-zinc-500">Pre-service operations</p><h1 className="mt-2 text-3xl font-semibold">Guest Updates Review</h1><p className="mt-3 text-sm text-zinc-400">Review guest-provided information before it becomes operational context. Nothing is applied or communicated automatically.</p></header>
 <form className="grid gap-3 rounded-2xl border border-white/10 bg-white/[0.02] p-5 md:grid-cols-3 xl:grid-cols-6"><label className="text-xs text-zinc-500">Business<select name="business" defaultValue={business?.business_id||""} className="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2">{businesses.map(x=><option key={x.business_id} value={x.business_id}>{Array.isArray(x.businesses)?x.businesses[0]?.name:x.businesses?.name}</option>)}</select></label><label className="text-xs text-zinc-500">Restaurant<select name="restaurant" defaultValue={restaurant?.id||""} className="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2"><option value="">All</option>{(restaurants||[]).map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label className="text-xs text-zinc-500">Service date<input type="date" name="date" defaultValue={q.date||""} className="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2"/></label><Filter name="status" value={q.status||"pending_review"} options={statuses}/><Filter name="type" value={q.type||""} options={["communication_preferences","guest_notes"]}/><div className="flex items-end"><button className="w-full rounded-lg bg-white px-4 py-2 text-sm font-medium text-black">Filter queue</button></div></form>
 {result.error?<p className="rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-red-200">{result.error.message}</p>:null}<section className="overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-full text-left text-sm"><thead className="bg-white/[0.03] text-xs uppercase tracking-wider text-zinc-500"><tr><th className="px-4 py-3">Guest</th><th className="px-4 py-3">Service</th><th className="px-4 py-3">Update</th><th className="px-4 py-3">Submitted</th><th className="px-4 py-3">Status</th><th/></tr></thead><tbody className="divide-y divide-white/5">{rows.map(row=><tr key={row.submission_id}><td className="px-4 py-4"><p className="font-medium">{row.guest_name}</p><p className="text-xs text-zinc-500">{row.guest_email||row.guest_phone||"No contact"} · {row.party_size??"—"} guests</p></td><td className="px-4 py-4">{row.restaurant_name}<p className="text-xs text-zinc-500">{row.reservation_date||"Date pending"} · {row.reservation_time?.slice(0,5)||"Time pending"}</p></td><td className="max-w-md px-4 py-4"><p className="capitalize">{row.update_type.replaceAll("_"," ")}</p><p className="mt-1 truncate text-xs text-zinc-500">{row.preview}</p></td><td className="px-4 py-4 text-zinc-400">{new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(row.submitted_at))}</td><td className="px-4 py-4"><Badge value={row.review_status}/></td><td className="px-4 py-4 text-right"><Link href={`/${locale}/business/guest-updates/${row.submission_id}`} className="rounded-lg border border-white/10 px-3 py-2 hover:bg-white/5">Review</Link></td></tr>)}{!rows.length?<tr><td colSpan={6} className="px-4 py-8 text-center text-zinc-500">No guest updates match these filters.</td></tr>:null}</tbody></table></section></div>;
}
function Filter({name,value,options}:{name:string;value:string;options:string[]}){return <label className="text-xs capitalize text-zinc-500">{name}<select name={name} defaultValue={value} className="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2"><option value="">All</option>{options.map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select></label>}
function Badge({value}:{value:string}){return <span className={`rounded-full border px-3 py-1 text-xs ${value==="pending_review"?"border-amber-300/30 bg-amber-300/10 text-amber-100":"border-emerald-300/30 bg-emerald-300/10 text-emerald-100"}`}>{value.replaceAll("_"," ")}</span>}
