"use client";

import {useActionState,useState} from "react";
import {acknowledgeHandoff,addBriefingNote,closeBriefing,createHandoff,prepareBriefing,reviewBriefingItem} from "./actions";
const initialBriefingState={status:"idle" as const,message:""};

type Handoff={id:string;status:string;target_type:string;message:string|null;parent_handoff_id:string|null};
type Props={briefingId:string;status:string;handoffs:Handoff[];reservations:{reservation_id:string;guest_name:string}[];briefingText:string};
export function BriefingControls({briefingId,status,handoffs,reservations,briefingText}:Props){
 const [prepareState,prepareAction,preparePending]=useActionState(prepareBriefing,initialBriefingState);
 const [noteState,noteAction,notePending]=useActionState(addBriefingNote,initialBriefingState);
 const [reviewState,reviewAction,reviewPending]=useActionState(reviewBriefingItem,initialBriefingState);
 const [handoffState,handoffAction,handoffPending]=useActionState(createHandoff,initialBriefingState);
 const [ackState,ackAction,ackPending]=useActionState(acknowledgeHandoff,initialBriefingState);
 const [closeState,closeAction,closePending]=useActionState(closeBriefing,initialBriefingState);
 const [copied,setCopied]=useState(false);
 const pendingHandoffs=handoffs.filter(h=>h.status==="created"&&!handoffs.some(a=>a.parent_handoff_id===h.id&&a.status==="acknowledged"));
 return <div className="space-y-4 rounded-2xl border border-white/10 bg-white/[0.03] p-5">
  <div className="flex flex-wrap gap-3">
   <form action={prepareAction}><input type="hidden" name="briefing_id" value={briefingId}/><button disabled={status!=="draft"||preparePending} className="rounded-lg bg-white px-4 py-2 text-sm font-medium text-black disabled:opacity-40">Prepare briefing</button></form>
   <button type="button" onClick={async()=>{await navigator.clipboard.writeText(briefingText);setCopied(true)}} className="rounded-lg border border-white/10 px-4 py-2 text-sm hover:bg-white/5">{copied?"Copied":"Copy briefing"}</button>
   <button type="button" onClick={()=>window.print()} className="rounded-lg border border-white/10 px-4 py-2 text-sm hover:bg-white/5">Print</button>
  </div>
  <Message states={[prepareState,noteState,reviewState,handoffState,ackState,closeState]}/>
  <div className="grid gap-4 lg:grid-cols-2">
   <form action={noteAction} className="space-y-3 rounded-xl border border-white/10 p-4"><h3 className="font-medium">Append briefing note</h3><input type="hidden" name="briefing_id" value={briefingId}/><select name="reservation_id" className="w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-sm"><option value="">Whole briefing</option>{reservations.map(r=><option key={r.reservation_id} value={r.reservation_id}>{r.guest_name}</option>)}</select><textarea name="note" required maxLength={2000} rows={3} className="w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-sm" placeholder="Operational context for this briefing only"/><button disabled={status==="closed"||notePending} className="rounded-lg bg-white px-4 py-2 text-sm text-black disabled:opacity-40">Add note</button></form>
   <form action={reviewAction} className="space-y-3 rounded-xl border border-white/10 p-4"><h3 className="font-medium">Mark item reviewed</h3><input type="hidden" name="briefing_id" value={briefingId}/><select name="item_type" className="w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-sm">{["reservation","dietary","guest_update","communication","capacity","note","other"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><input name="item_key" required maxLength={200} className="w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-sm" placeholder="Item key or short label"/><select name="reservation_id" className="w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-sm"><option value="">Not reservation-specific</option>{reservations.map(r=><option key={r.reservation_id} value={r.reservation_id}>{r.guest_name}</option>)}</select><input name="review_note" maxLength={1000} className="w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-sm" placeholder="Optional review note"/><button disabled={status==="closed"||reviewPending} className="rounded-lg bg-white px-4 py-2 text-sm text-black disabled:opacity-40">Record review</button></form>
   <form action={handoffAction} className="space-y-3 rounded-xl border border-white/10 p-4"><h3 className="font-medium">Create staff handoff</h3><input type="hidden" name="briefing_id" value={briefingId}/><select name="target_type" className="w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-sm">{["dining_room","kitchen","management","sommelier","other"].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select><textarea name="message" maxLength={2000} rows={3} className="w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-sm" placeholder="Optional handoff context"/><button disabled={!(["prepared","handed_off","acknowledged"].includes(status))||handoffPending} className="rounded-lg bg-white px-4 py-2 text-sm text-black disabled:opacity-40">Create handoff</button></form>
   <form action={closeAction} className="space-y-3 rounded-xl border border-white/10 p-4"><h3 className="font-medium">Close briefing</h3><input type="hidden" name="briefing_id" value={briefingId}/><input name="reason" required maxLength={1000} className="w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-sm" placeholder="Reason for closing"/><button disabled={status==="closed"||closePending} onClick={e=>{if(!confirm("Close this briefing? This is explicit and audited."))e.preventDefault()}} className="rounded-lg border border-amber-300/30 px-4 py-2 text-sm text-amber-100 disabled:opacity-40">Close briefing</button></form>
  </div>
  {pendingHandoffs.length?<div className="space-y-3 rounded-xl border border-amber-300/20 bg-amber-300/5 p-4"><h3 className="font-medium text-amber-100">Pending handoffs</h3>{pendingHandoffs.map(h=><form key={h.id} action={ackAction} className="flex flex-wrap items-center gap-3"><input type="hidden" name="handoff_id" value={h.id}/><span className="text-sm text-zinc-300">{h.target_type.replaceAll("_"," ")}: {h.message||"No message"}</span><input name="acknowledgement_note" maxLength={1000} className="min-w-64 rounded-lg border border-white/10 bg-black px-3 py-2 text-sm" placeholder="Optional acknowledgement note"/><button disabled={ackPending} className="rounded-lg bg-white px-3 py-2 text-sm text-black">Acknowledge</button></form>)}</div>:null}
 </div>;
}
function Message({states}:{states:{status:string;message:string}[]}){const state=[...states].reverse().find(s=>s.status!=="idle"&&s.message);return state?<p className={`rounded-lg border p-3 text-sm ${state.status==="error"?"border-red-400/20 bg-red-400/10 text-red-200":"border-emerald-400/20 bg-emerald-400/10 text-emerald-100"}`}>{state.message}</p>:null;}
