import Link from "next/link";
import {createClient} from "@/lib/supabase/server";
import {createBriefing} from "./actions";

export const dynamic="force-dynamic";
type Membership={business_id:string;businesses:{name:string}|{name:string}[]|null};
type Restaurant={id:string;name:string};
type Period={id:string;name:string;start_time:string;end_time:string;restaurant_id:string};
type Row={briefing_id:string;restaurant_name:string;service_date:string;service_period_name:string|null;status:string;created_at:string;prepared_at:string|null;pending_handoffs:number;acknowledgements:number;notes_count:number;reviewed_items_count:number};
const statuses=["draft","prepared","handed_off","acknowledged","closed"];
const today=()=>new Date().toISOString().slice(0,10);
export default async function BriefingsPage({params,searchParams}:{params:Promise<{locale:string}>;searchParams:Promise<{business?:string;restaurant?:string;date?:string;period?:string;status?:string}>}){
 const {locale}=await params,q=await searchParams,supabase=await createClient();
 const {data:memberships=[]}=await supabase.from("business_memberships").select("business_id,businesses(name)");
 const businesses=(memberships||[]) as unknown as Membership[];const business=businesses.find(x=>x.business_id===q.business)||businesses[0];
 const {data:restaurants=[]}=business?await supabase.from("restaurants").select("id,name").eq("business_id",business.business_id).order("name"):{data:[]};
 const restaurant=(restaurants as Restaurant[]).find(x=>x.id===q.restaurant)||(restaurants as Restaurant[])[0];
 const {data:periods=[]}=business?await supabase.from("business_service_periods").select("id,name,start_time,end_time,restaurant_id").eq("business_id",business.business_id).eq("active",true).order("start_time"):{data:[]};
 const visiblePeriods=(periods as Period[]).filter(p=>!restaurant||p.restaurant_id===restaurant.id);const period=visiblePeriods.find(p=>p.id===q.period);
 const serviceDate=q.date||today();
 const result=business?await supabase.rpc("list_pre_service_briefings",{p_business_id:business.business_id,p_restaurant_id:restaurant?.id||null,p_service_date:serviceDate||null,p_service_period_id:period?.id||null,p_status:q.status||null}):{data:[],error:null};
 const rows=(result.data||[]) as Row[];
 return <div className="space-y-6 p-6 text-white"><header className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><p className="text-xs uppercase tracking-[0.2em] text-zinc-500">Pre-service operations</p><h1 className="mt-2 text-3xl font-semibold">Service Briefings</h1><p className="mt-3 text-sm text-zinc-400">Create controlled, human-reviewed briefings for sala, cozinha and management. No decisions or communications are automated.</p></header>
  <form className="grid gap-3 rounded-2xl border border-white/10 bg-white/[0.02] p-5 md:grid-cols-3 xl:grid-cols-6"><Select name="business" value={business?.business_id||""} options={businesses.map(x=>({value:x.business_id,label:Array.isArray(x.businesses)?x.businesses[0]?.name||x.business_id:x.businesses?.name||x.business_id}))}/><Select name="restaurant" value={restaurant?.id||""} options={(restaurants as Restaurant[]).map(x=>({value:x.id,label:x.name}))}/><label className="text-xs text-zinc-500">Operational date<input type="date" name="date" defaultValue={serviceDate} className="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2"/></label><Select name="period" value={period?.id||""} options={[{value:"",label:"All periods"},...visiblePeriods.map(x=>({value:x.id,label:`${x.name} (${x.start_time.slice(0,5)}-${x.end_time.slice(0,5)})`}))]}/><Select name="status" value={q.status||""} options={[{value:"",label:"All states"},...statuses.map(x=>({value:x,label:x.replaceAll("_"," ")}))]}/><div className="flex items-end"><button className="w-full rounded-lg bg-white px-4 py-2 text-sm font-medium text-black">Filter</button></div></form>
  <form action={createBriefing} className="flex flex-wrap items-end gap-3 rounded-2xl border border-emerald-300/20 bg-emerald-300/5 p-5"><input type="hidden" name="locale" value={locale}/><input type="hidden" name="restaurant_id" value={restaurant?.id||""}/><input type="hidden" name="service_date" value={serviceDate}/><input type="hidden" name="service_period_id" value={period?.id||""}/><div><p className="font-medium text-emerald-100">Create briefing explicitly</p><p className="text-sm text-zinc-400">Uses the selected restaurant, operational date and service period filter. Existing open briefing is reused.</p></div><button disabled={!restaurant} className="rounded-lg bg-white px-4 py-2 text-sm font-medium text-black disabled:opacity-40">Create / open briefing</button></form>
  {result.error?<p className="rounded-xl border border-red-400/20 bg-red-400/10 p-4 text-red-200">{result.error.message}</p>:null}<section className="overflow-x-auto rounded-2xl border border-white/10"><table className="min-w-full text-left text-sm"><thead className="bg-white/[0.03] text-xs uppercase tracking-wider text-zinc-500"><tr><th className="px-4 py-3">Briefing</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Handoff</th><th className="px-4 py-3">Controls</th><th/></tr></thead><tbody className="divide-y divide-white/5">{rows.map(row=><tr key={row.briefing_id}><td className="px-4 py-4"><p className="font-medium">{row.restaurant_name}</p><p className="text-xs text-zinc-500">{row.service_date} · {row.service_period_name||"All periods"}</p></td><td className="px-4 py-4"><Badge value={row.status}/></td><td className="px-4 py-4 text-zinc-400">{row.pending_handoffs} pending · {row.acknowledgements} ack</td><td className="px-4 py-4 text-zinc-400">{row.notes_count} notes · {row.reviewed_items_count} reviewed</td><td className="px-4 py-4 text-right"><Link href={`/${locale}/business/briefings/${row.briefing_id}`} className="rounded-lg border border-white/10 px-3 py-2 hover:bg-white/5">Open</Link></td></tr>)}{!rows.length?<tr><td colSpan={5} className="px-4 py-8 text-center text-zinc-500">No briefings match these filters.</td></tr>:null}</tbody></table></section></div>;
}
function Select({name,value,options}:{name:string;value:string;options:{value:string;label:string}[]}){return <label className="text-xs capitalize text-zinc-500">{name}<select name={name} defaultValue={value} className="mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2">{options.map(x=><option key={`${name}-${x.value}`} value={x.value}>{x.label}</option>)}</select></label>}
function Badge({value}:{value:string}){const tone=value==="closed"?"border-zinc-500/30 text-zinc-300":value==="draft"?"border-amber-300/30 bg-amber-300/10 text-amber-100":"border-emerald-300/30 bg-emerald-300/10 text-emerald-100";return <span className={`rounded-full border px-3 py-1 text-xs ${tone}`}>{value.replaceAll("_"," ")}</span>}
