"use client";
import { useActionState } from "react";
import type { AvailabilityBusiness, AvailabilityRestaurant, BusinessServicePeriod } from "@/lib/availability";
import { OPERATIONAL_NOTE_TYPES, operationalNoteLabels } from "@/lib/operational-capacity";
import { endCapacityOverride, endOperationalNote, initialReviewActionState, saveCapacityOverride, saveOperationalNote } from "./review-actions";
const input = "mt-1 w-full rounded-lg border border-white/10 bg-black px-3 py-2 text-sm text-white disabled:opacity-50";
function canManage(items: AvailabilityBusiness[], id: string) { return ["owner", "manager"].includes(items.find((x) => x.id === id)?.role || ""); }
function Feedback({ state }: { state: { status: string; message: string } }) { return state.message ? <p aria-live="polite" className={state.status === "error" ? "text-xs text-red-300" : "text-xs text-emerald-300"}>{state.message}</p> : null; }
export function CapacityOverrideForm({ businesses, restaurant, periods, defaultDate }: { businesses: AvailabilityBusiness[]; restaurant: AvailabilityRestaurant; periods: BusinessServicePeriod[]; defaultDate: string }) {
 const [state, action, pending] = useActionState(saveCapacityOverride, initialReviewActionState); const allowed = canManage(businesses, restaurant.business_id);
 return <form action={action} className="grid gap-3 md:grid-cols-4"><input type="hidden" name="business_id" value={restaurant.business_id} /><input type="hidden" name="restaurant_id" value={restaurant.id} /><label className="text-xs text-zinc-500">Date<input className={input} type="date" name="operational_date" required defaultValue={defaultDate} disabled={!allowed || pending} /></label><label className="text-xs text-zinc-500">Service period<select className={input} name="service_period_id" required disabled={!allowed || pending}><option value="">Select period</option>{periods.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-xs text-zinc-500">Adjusted capacity<input className={input} type="number" min={0} max={5000} name="adjusted_capacity" required disabled={!allowed || pending} /></label><label className="text-xs text-zinc-500">Reason<input className={input} name="reason" maxLength={500} required placeholder="Reduced team, private service..." disabled={!allowed || pending} /></label><div className="flex items-center gap-3 md:col-span-full"><button disabled={!allowed || pending} className="rounded-lg bg-amber-200 px-4 py-2 text-sm font-medium text-black disabled:opacity-50">{pending ? "Saving..." : "Apply manual override"}</button><Feedback state={state} />{!allowed ? <span className="text-xs text-zinc-600">Owner or manager role required.</span> : null}</div></form>;
}
export function OperationalNoteForm({ businesses, restaurant, periods, defaultDate }: { businesses: AvailabilityBusiness[]; restaurant: AvailabilityRestaurant; periods: BusinessServicePeriod[]; defaultDate: string }) {
 const [state, action, pending] = useActionState(saveOperationalNote, initialReviewActionState); const allowed = canManage(businesses, restaurant.business_id);
 return <form action={action} className="grid gap-3 md:grid-cols-4"><input type="hidden" name="business_id" value={restaurant.business_id} /><input type="hidden" name="restaurant_id" value={restaurant.id} /><label className="text-xs text-zinc-500">Date<input className={input} type="date" name="operational_date" required defaultValue={defaultDate} disabled={!allowed || pending} /></label><label className="text-xs text-zinc-500">Service period<select className={input} name="service_period_id" disabled={!allowed || pending}><option value="">All periods</option>{periods.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="text-xs text-zinc-500">Note type<select className={input} name="note_type" disabled={!allowed || pending}>{OPERATIONAL_NOTE_TYPES.map((type) => <option key={type} value={type}>{operationalNoteLabels[type]}</option>)}</select></label><label className="text-xs text-zinc-500">Operational note<input className={input} name="note" maxLength={1000} required placeholder="Context for the service team" disabled={!allowed || pending} /></label><div className="flex items-center gap-3 md:col-span-full"><button disabled={!allowed || pending} className="rounded-lg border border-white/15 px-4 py-2 text-sm disabled:opacity-50">{pending ? "Saving..." : "Add operational note"}</button><Feedback state={state} /></div></form>;
}
export function EndOverrideForm({ overrideId, allowed }: { overrideId: string; allowed: boolean }) { const [state, action, pending] = useActionState(endCapacityOverride, initialReviewActionState); return <form action={action} className="mt-2 flex max-w-md items-end gap-2"><input type="hidden" name="override_id" value={overrideId} /><label className="flex-1 text-xs text-zinc-500">Reason to end<input className={input} name="reason" required maxLength={500} disabled={!allowed || pending} /></label><button className="rounded-lg border border-amber-300/30 px-3 py-2 text-xs text-amber-200 disabled:opacity-50" disabled={!allowed || pending}>End override</button><Feedback state={state} /></form>; }
export function EndNoteForm({ noteId, allowed }: { noteId: string; allowed: boolean }) { const [state, action, pending] = useActionState(endOperationalNote, initialReviewActionState); return <form action={action} className="mt-2 flex items-end gap-2"><input type="hidden" name="note_id" value={noteId} /><label className="flex-1 text-xs text-zinc-600">Reason to close<input className={input} name="reason" required maxLength={500} disabled={!allowed || pending} /></label><button className="rounded-lg border border-white/10 px-2 py-2 text-xs disabled:opacity-50" disabled={!allowed || pending}>Close note</button><Feedback state={state} /></form>; }
