import Link from "next/link";
import {notFound} from "next/navigation";
import {createClient} from "@/lib/supabase/server";
import {ReviewControls} from "./review-controls";
export const dynamic="force-dynamic";
type Submission={id:string;reservation_id:string;submission_type:string;preferred_channel:string|null;preferred_language:string|null;can_contact_about_reservation:boolean|null;allergies_dietary_note:string|null;special_occasion_note:string|null;arrival_accessibility_note:string|null;general_note:string|null;created_at:string};
export default async function GuestUpdateDetail({params}:{params:Promise<{locale:string;id:string}>}){const {locale,id}=await params,supabase=await createClient();
 const {data:submission}=await supabase.from("reservation_guest_submissions").select("id,reservation_id,submission_type,preferred_channel,preferred_language,can_contact_about_reservation,allergies_dietary_note,special_occasion_note,arrival_accessibility_note,general_note,created_at").eq("id",id).maybeSingle();if(!submission)notFound();
 const [reservationResult,reviewResult,notesResult]=await Promise.all([supabase.from("reservations").select("guest_name,guest_email,guest_phone,requested_date,requested_time,party_size,status").eq("id",submission.reservation_id).maybeSingle(),supabase.from("reservation_guest_submission_reviews").select("review_status,review_reason,reviewed_by,reviewed_at,linked_internal_note_id,linked_communication_id").eq("submission_id",id).maybeSingle(),supabase.from("reservation_internal_notes").select("id,note,created_at").eq("canonical_reservation_id",submission.reservation_id).order("created_at",{ascending:false}).limit(5)]);
 const item=submission as Submission,reservation=reservationResult.data,review=reviewResult.data;
 return <div className="space-y-6 p-6 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><Link href={`/${locale}/business/guest-updates`} className="text-sm text-zinc-400 hover:text-white">← Guest updates queue</Link><span className="rounded-full border border-amber-300/30 bg-amber-300/10 px-3 py-1 text-xs text-amber-100">{review?.review_status?.replaceAll("_"," ")||"pending review"}</span></div><header className="rounded-2xl border border-white/10 bg-white/[0.03] p-6"><p className="text-xs uppercase tracking-[0.2em] text-zinc-500">Guest-provided update</p><h1 className="mt-2 text-3xl font-semibold">{reservation?.guest_name||"Guest update"}</h1><p className="mt-3 text-sm text-zinc-400">Original submission preserved unchanged. Staff review determines operational relevance.</p></header>
 <section className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.02] p-5"><h2 className="text-sm font-medium uppercase tracking-[0.15em] text-zinc-500">Original submission</h2><div className="mt-4 space-y-2 text-sm"><p><span className="text-zinc-500">Type:</span> {item.submission_type.replaceAll("_"," ")}</p><p><span className="text-zinc-500">Submitted:</span> {new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(new Date(item.created_at))}</p>{item.preferred_channel?<p>Preferred channel: {item.preferred_channel} · {item.preferred_language} · contact {item.can_contact_about_reservation?"permitted":"not permitted"}</p>:null}{item.allergies_dietary_note?<p><span className="text-zinc-500">Allergies / dietary:</span> {item.allergies_dietary_note}</p>:null}{item.special_occasion_note?<p><span className="text-zinc-500">Occasion:</span> {item.special_occasion_note}</p>:null}{item.arrival_accessibility_note?<p><span className="text-zinc-500">Arrival / accessibility:</span> {item.arrival_accessibility_note}</p>:null}{item.general_note?<p><span className="text-zinc-500">General:</span> {item.general_note}</p>:null}</div></div><div className="rounded-2xl border border-white/10 bg-white/[0.02] p-5"><h2 className="text-sm font-medium uppercase tracking-[0.15em] text-zinc-500">Reservation context</h2><div className="mt-4 space-y-2 text-sm"><p>{reservation?.requested_date||"Date pending"} · {reservation?.requested_time?.slice(0,5)||"Time pending"} · {reservation?.party_size??"—"} guests</p><p className="text-zinc-400">{reservation?.guest_email||reservation?.guest_phone||"No guest contact recorded"}</p><p><span className="text-zinc-500">Reservation status:</span> {reservation?.status}</p></div><h3 className="mt-5 text-xs uppercase tracking-[0.15em] text-zinc-500">Recent internal notes</h3><div className="mt-2 space-y-2">{(notesResult.data||[]).map(note=><p key={note.id} className="rounded-lg border border-white/10 bg-black/20 p-3 text-sm text-zinc-300">{note.note}</p>)}{!notesResult.data?.length?<p className="text-sm text-zinc-500">No internal notes.</p>:null}</div></div></section>
 <section className="rounded-2xl border border-white/10 bg-white/[0.02] p-5"><h2 className="text-sm font-medium uppercase tracking-[0.15em] text-zinc-500">Review decision</h2><div className="mt-4">{review?<div className="space-y-2 text-sm"><p className="font-medium capitalize">{review.review_status.replaceAll("_"," ")}</p><p className="text-xs text-zinc-500">{new Date(review.reviewed_at).toLocaleString()} · actor {review.reviewed_by}</p>{review.review_reason?<p><span className="text-zinc-500">Review note:</span> {review.review_reason}</p>:null}{review.linked_internal_note_id?<p>Linked internal note: {review.linked_internal_note_id}</p>:null}{review.linked_communication_id?<p>Linked communication draft: {review.linked_communication_id}</p>:null}</div>:<ReviewControls submissionId={id}/>}</div></section></div>;
}
